import Head from "next/head";
import styles from "../styles/Home.module.css";
import Post from "../components/Post";
import { useSelector, useDispatch } from "react-redux";
import { useState } from "react";
import Form from "../components/Form";
import { addBlog, deleteBlog, updateBlog, setBlogs } from "../store/blogSlice";
import { initialiseStore } from "../store/store";

export default function Home() {
  const dispatch = useDispatch();
  const blogLists = useSelector((state) => state.blogs.blogLists);
  const user = useSelector((state) => state.user);
  const [showAddForm, setShowAddForm] = useState(false);
  const [showEditForm, setShowEditForm] = useState(false);
  const [blog, setBlog] = useState({});

  const handleDelete = (blogId) => {
    dispatch(deleteBlog({ id: blogId }));
  };

  const handleAddSubmit = (e) => {
    e.preventDefault();
    setShowAddForm(false);
    dispatch(addBlog({ ...blog, id: Date.now() }));
    setBlog({});
  };

  const handleEditSubmit = (e) => {
    e.preventDefault();
    setShowEditForm(false);
    dispatch(
      updateBlog({
        id: blog.id,
        name: blog.name,
        population: blog.population,
      })
    );

    setBlog({});
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <h1>All Posts</h1>
      </header>

      <main className={styles.main}>
        <button className={styles.button} onClick={() => setShowAddForm(true)}>
          Add Post
        </button>
        {(showAddForm || showEditForm) && (
          <Form
            handleSubmit={showAddForm ? handleAddSubmit : handleEditSubmit}
            blog={blog}
            setBlog={setBlog}
          />
        )}

        {blogLists.map((blog) => (
          <Post
            key={blog.id}
            blog={blog}
            handleDelete={() => handleDelete(blog.id)}
            handleEdit={() => {
              setBlog(blog);
              setShowEditForm(true);
            }}
          />
        ))}
      </main>
    </div>
  );
}

export async function getStaticProps(ctx) {
  const res = await fetch("http://localhost:3000/api/blogs");
  const blogLists = await res.json();

  return {
    props: {
      initialReduxState: { blogs: { blogLists } },
    },
  };
}
